### PR TITLE
bump PLANETSCOPE stac version to 1.0.0

### LINKED ISSUE #54: PLANETSCOPE stac version
PLANETSCOPE stac version is currently still at  0.9.0, we should look in to changing this to 1.0.0

### PR DESCRIPTION
**Pull request by guss84**
Fixes #54 

Updated the version to 1.0.0, added missing `type` attribute and validated the json file with https://github.com/stac-utils/stac-validator

### CODE REVIEW

**Review by dthiex — CHANGES_REQUESTED** [review]
Let's also update the version within `tests\fixtures\collection_information\PLANETSCOPE.json` for consistence.

**Comment by guss84** [comment]
> Let's also update the version within `tests\fixtures\collection_information\PLANETSCOPE.json` for consistence.

Good point, updated the stac version in the test fixture as well

**Review by dthiex — APPROVED** [review]

**Comment by dthiex** [comment]
@guss84 Can you pls. check why the tests are failing here? I checked the stac file and it looks fine. Once the tests are working again, we can merge this.

**Comment by guss84** [comment]
> @guss84 Can you pls. check why the tests are failing here? I checked the stac file and it looks fine. Once the tests are working again, we can merge this.

The tests failed because the docker-compose script had to be updated. This was done with https://github.com/Open-EO/openeo-sentinelhub-python-driver/pull/86/commits/e967e6d1ad691173c2997fd17f85e62e56dfd33f

**Pull request merged**
